import os
import json

def main():
    model_path = "/Users/kamran/Documents/ERAV5/session2/model/tokenizer.json"
    widget_dir = "/Users/kamran/Documents/ERAV5/session2/widget"
    data_dir = "/Users/kamran/Documents/ERAV5/session2/data"
    
    if not os.path.exists(model_path):
        print("Error: train_bpe.py must be run first to generate model/tokenizer.json")
        return
        
    os.makedirs(widget_dir, exist_ok=True)
    
    # 1. Load tokenizer data
    with open(model_path, "r", encoding="utf-8") as f:
        tokenizer_data = json.load(f)
        
    # Write to widget/tokenizer_data.js
    js_tokenizer_path = os.path.join(widget_dir, "tokenizer_data.js")
    with open(js_tokenizer_path, "w", encoding="utf-8") as f:
        f.write("// Autogenerated from model/tokenizer.json\n")
        f.write("window.TOKENIZER_DATA = ")
        json.dump(tokenizer_data, f, ensure_ascii=False, indent=2)
        f.write(";\n")
    print(f"Generated {js_tokenizer_path}")
    
    # 2. Load sample texts from data/
    sample_texts = {}
    langs = tokenizer_data["langs"]
    for lang in langs:
        text_path = os.path.join(data_dir, f"india_{lang}.txt")
        if os.path.exists(text_path):
            with open(text_path, "r", encoding="utf-8") as f:
                # Get the first 1500 characters as a clean sample
                sample_texts[lang] = f.read()[:2000]
        else:
            sample_texts[lang] = f"Sample text for {lang} not found."
            
    # Write to widget/sample_texts.js
    js_samples_path = os.path.join(widget_dir, "sample_texts.js")
    with open(js_samples_path, "w", encoding="utf-8") as f:
        f.write("// Autogenerated from data text files\n")
        f.write("window.SAMPLE_TEXTS = ")
        json.dump(sample_texts, f, ensure_ascii=False, indent=2)
        f.write(";\n")
    print(f"Generated {js_samples_path}")

if __name__ == "__main__":
    main()
